### ISSUE TITLE
Writing 0 to coils error?

### ISSUE THREAD

**Issue by LunarMongoose** [tallakt/modbus-cli#11]
Currently I am observing some peculiar behavior. Whenever I write a 0 to coils it overwrites everything higher in the address space. For example if I write a 1 to 101 and 102 and then read I get this
101 1
102 1
Then if I write a 0 to 101 and read I get this
101 0 
102 0
I'm not sure if this is intended behavior but it is weird. Any response would be helpful
```
:~/hello$ modbus read 10.7.8.131 101 2
101        1
102        1
:~/hello$ modbus write 10.7.8.131 101 0
:~/hello$ modbus read 10.7.8.131 101 2
101        0
102        0
:~/hello$

**Comment by LunarMongoose** [comment]
Update. This is due to the fact that all commands sent are being interpreted as write multiple coils even though there is only supposed to be one coil being written. This to me looks like unintended behavior. Correct me if I am wrong

**Comment by tallakt** [comment]
I think maybe write multiple coils may be written as a byte in the modbus server, or the modbus write coils command is done bytewise in the rmodbus package that midbus-cli depends on

**Comment by tallakt** [comment]
After reading rhe rmodbus code, i believe the issue is probably in your server. Writing a single item or multiple items is mostly redundant in modbus, in general I just use the multiple function codes to make life simpler

**Comment by LunarMongoose** [comment]
Alright this makes sense. However, when I sniff the traffic between my linux box and the OpenPLC server  I have running with wireshark the packets sent are shown as write multiple registers with the correct function code and everything. To me it seems like the server is interpreting whatever packets are being sent by modbus-cli

**Comment by tallakt** [comment]
How many registers are being sent in witeshark? Using write many coils is correct

**Comment by LunarMongoose** [comment]
whenever you do a write like that it writes the first coil correctly but then it writes 7 other coils to 0 after
'''
:~/modbus_scripts$ modbus read 10.7.8.131 2 10
2          1
3          1
4          1
5          1
6          1
7          1
8          1
9          1
10         1
11         1
lunar@LAPTOP-GSQD0G9F:~/modbus_scripts$ modbus write 10.7.8.131 2 1
lunar@LAPTOP-GSQD0G9F:~/modbus_scripts$ modbus read 10.7.8.131 2 10
2          1
3          0
4          0
5          0
6          0
7          0
8          0
9          0
10         1
11         1
:~/modbus_scripts$
