### ISSUE TITLE
Modbus-cli NoMethodError with dump and write

### ISSUE THREAD

**Issue by mbround18** [tallakt/modbus-cli#8]
Hello, 
I know this project hasnt had work done on it in a couple of years but as of recently I am receiving issues on write and dump commands. If you are available would you be able to provide me with some assistance? Below is the errors I'm getting.

modbus write -w -p 38338 127.0.0.1 400001 1
/home/username/.rvm/gems/ruby-2.2.0/gems/modbus-cli-0.0.9/lib/modbus-cli/write_command.rb:79:in `int_parameter': undefined method `map' for "1":String (NoMethodError)
	from /home/username/.rvm/gems/ruby-2.2.0/gems/modbus-cli-0.0.9/lib/modbus-cli/write_command.rb:25:in `block in <class:WriteCommand>'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/attribute/declaration.rb:40:in `instance_exec'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/attribute/declaration.rb:40:in `block in define_appender_for'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/attribute/instance.rb:57:in `take'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:13:in `block (2 levels) in parse_parameters'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:12:in `each'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:12:in `block in parse_parameters'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:10:in `each'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:10:in `parse_parameters'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:53:in `parse'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:66:in `run'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/modbus-cli-0.0.9/bin/modbus:6:in `<top (required)>'
	from /home/username/.rvm/gems/ruby-2.2.0/bin/modbus:23:in `load'
	from /home/username/.rvm/gems/ruby-2.2.0/bin/modbus:23:in `<main>'
	from /home/username/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/username/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

modbus dump -p 38338 -h 127.0.0.1 -o 400001 mybackup.yml
/home/username/.rvm/gems/ruby-2.2.0/gems/modbus-cli-0.0.9/lib/modbus-cli/dump_command.rb:11:in `block in <class:DumpCommand>': undefined method `map' for "mybackup.yml":String (NoMethodError)
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/attribute/declaration.rb:40:in `instance_exec'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/attribute/declaration.rb:40:in `block in define_appender_for'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/attribute/instance.rb:57:in `take'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:13:in `block (2 levels) in parse_parameters'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:12:in `each'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:12:in `block in parse_parameters'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:10:in `each'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/parameter/parsing.rb:10:in `parse_parameters'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:53:in `parse'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:66:in `run'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /home/username/.rvm/gems/ruby-2.2.0/gems/modbus-cli-0.0.9/bin/modbus:6:in `<top (required)>'
	from /home/username/.rvm/gems/ruby-2.2.0/bin/modbus:23:in `load'
	from /home/username/.rvm/gems/ruby-2.2.0/bin/modbus:23:in `<main>'
	from /home/username/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/username/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by tallakt** [comment]
Hi. The project hasnt seen any updates because I assumed it was working ok. Thanks for your bugreport. Unfortunately I cannot address it immediately. I will try to find some time the next days and get back to you. If you don't hear anything, I woudl appreciate if you get in touch later (after a few days). I think the bug is related to a change in the Clamp library that I am using.

**Comment by mbround18** [comment]
Hey just following up, any updates?

**Comment by tallakt** [comment]
Thanks for the reminder. I hope the issues in question have been fixed. As I don't have access to a modbus device at the moment, I would appreciate any feedback if all of this did not work well..
