### ISSUE TITLE
How do I read a discrete input?

### ISSUE THREAD

**Issue by woodrowbarlow** [tallakt/modbus-cli#9]
Hello,

Thank you for the useful tool. I'm using it to test a TCP Modbus server that I'm writing.

Unless I'm mistaken, Modbus has four distinct address spaces:

* Coils (1 bit, read-write)
* Discrete Inputs (1 bit, read-only)
* Holding Registers (16 bits, read-write)
* Input Registers (16 bits, read-only)

I'm not accustomed to the addressing scheme you're using, but I've determined most of it.

```sh
# read the first coil (modbus function code 0x01)
modbus read <ip_address> 1 1
# read the first holding register (modbus function code 0x03)
modbus read <ip_address> 400001 1
# read the first input register (modbus function code 0x04)
modbus read <ip_address> 300001 1
```

How do I read from the Discrete Inputs (modbus function code 0x02) address space?

(In my implementation, this accesses different data to the coils.)

**Comment by tallakt** [comment]
They are not implemented unfortunately. The equipment I had never supported those. The adressing used is decribed on 

https://en.m.wikipedia.org/wiki/Modbus


This limits the number of addresses to 9,999 for each entity. A de facto referencing extends this to the maximum of 65,536.[12] It simply consists of adding one digit to the previous list:

coil numbers span from 000001 to 065536,
discrete input numbers span from 100001 to 165536,
input register numbers span from 300001 to 365536,
holding register numbers span from 400001 to 465536.
When using the extended referencing, all numberreferences must have exactly 6 digits. This avoids confusion between coils and other entities. For example, to know the difference between holding register #40001 and coil #40001, if coil #40001 is the target, it must appear as #040001.



Tallak


Sendt fra min telefon

**Comment by woodrowbarlow** [comment]
I see. Thank you.
